
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/json;

    sendfile        on;
    
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root html;  # 资源存放路径，告诉 Nginx 去哪里寻找请求的文件
        }

    }
	
    server {
        listen       18080;
        server_name  localhost;

        location / { # 处理前端静态页面
            root html/hmall-portal;  # 相对路径（相对于 Nginx 安装目录）
			# 请求 / → 实际读取 html/hmall-portal/index.html		
			
			# root /var/www;         # 绝对路径
			# 请求 /images/logo.jpg → 实际读取 /var/www/images/logo.jpg		
			
			# root /home/user/myapp; # 任意自定义目录
			# 请求 /index.html → 实际读取 /home/user/myapp/index.html
        }

		# 处理错误页面（特殊路径）
        error_page   500 502 503 504  /50x.html;
        location = /50x.html { # “=”：精确匹配 + 最高优先级
            root   html;
			# 请求 /50x.html → 实际读取 html/50x.html
        }
		
        location /api { # 处理后端请求
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://localhost:8080; # http://localhost:18081/api/user 转发到后端实际接口地址 http://localhost:8080/api/user
        }
    }
	
    server {
        listen       18081;
        server_name  localhost;
        # 指定前端项目所在的位置
        location / {
            root html/hmall-admin;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location /api {
            rewrite /api/(.*)  /$1 break;
            proxy_pass http://localhost:8080;
        }
    }
    
    # upstream backend {
    #     server 127.0.0.1:8081 max_fails=5 fail_timeout=10s weight=1;
    #     server 127.0.0.1:8082 max_fails=5 fail_timeout=10s weight=1;
    # }  
	
}



############################      #########################
	### root: 拼接
	### alias: 替换
	### 例如：http://example.com/static/app.js 
	location /static/ {
		root /usr/share/nginx/html;
		# 最终文件路径：
		# /usr/share/nginx/html + /static/app.js
		# = /usr/share/nginx/html/static/app.js
	}
	
	location /static/ {
		alias /usr/share/nginx/html/user/;
		# 最终文件路径：
		# 将 /static/ 替换为 /usr/share/nginx/html/user/ + app.js
		# = /usr/share/nginx/html/user/app.js
	}
	
	